# Generated by Django 4.1.7 on 2024-05-14 14:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crud", "0004_product_img"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="description",
            field=models.TextField(blank=True),
        ),
    ]
